services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: events
      POSTGRES_PASSWORD: MyPassword#
      POSTGRES_USER: admin
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080