micronaut:
  application:
    name: events
  server:
    port: 8080
datasources:
  default:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:events}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:MyPassword#}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
      sensitive: false
